# Inserts a blank line between shell prompts
add_newline = true

format = """
[┌──\\(](green)$username👾$hostname[\\)](green)$os $time| [$directory](bold blue)$all$line_break[└─](green)$character"""

[character]
#success_symbol = "💲"
success_symbol = "[\\$](bold blue)"
error_symbol = "[✗](bold red)"

[username]
disabled = false
style_user = 'blue bold'
style_root = 'red bold'
format = '[$user]($style)'
show_always = true

[hostname]
disabled = false
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold blue)'

[directory]
truncation_length = 5
truncation_symbol = '…/'

[time]
disabled = true
format = '🕙[\[$time\]]($style) '
use_12hr = true
style = 'green'

 
[os]
disabled = true
style = "bold blue"
format = " on [$symbol$name]($style)"
